staging:
  domain: "user@staging.mydomain.com"
  deploy_to: "/path/to/deploy"
  repository: "git@github.com:repo_owner/repo_name.git"
  branch: "staging"

production:
  domain: "user@mydomain.com"
  deploy_to: "/path/to/deploy"
  repository: "git@github.com:repo_owner/repo_name.git"
  branch: "master"
